### PR TITLE
Add script to run the k8s code generator

### PR DESCRIPTION
**Pull request by tpantelis**
Signed-off-by: Tom Pantelis <tompantelis@gmail.com>

### CODE REVIEW

**Comment by tpantelis** [comment]
@skitt

**Comment by tpantelis** [comment]
> The generator seems to be somewhat fragile — I had to delete `~/go/src/k8s.io/code-generator` entirely to get this to work — but this will do for now ;-).

Can you elaborate? Had you previously done 'go get /k8s.io/code-generator'? If so, then it would've been using the current master which generates incompatible code with prior k8s API versions causing compilation errors in subM. Hence the reason for retrieving the prior 1.14 version.

**Comment by skitt** [comment]
> > The generator seems to be somewhat fragile — I had to delete `~/go/src/k8s.io/code-generator` entirely to get this to work — but this will do for now ;-).
> 
> Can you elaborate? Had you previously done 'go get /k8s.io/code-generator'? If so, then it would've been using the current master which generates incompatible code with prior k8s API versions causing compilation errors in subM. Hence the reason for retrieving the prior 1.14 version.

I had previously run `go get k8s.io/code-generator`, and as a result I didn’t have the dependencies; running the code generator then fails with

```
cmd/defaulter-gen/args/args.go:23:2: cannot find package "k8s.io/gengo/args" in any of:
	/usr/lib/golang/src/k8s.io/gengo/args (from $GOROOT)
	/home/skitt/go/src/k8s.io/gengo/args (from $GOPATH)
cmd/defaulter-gen/args/args.go:24:2: cannot find package "k8s.io/gengo/examples/defaulter-gen/generators" in any of:
	/usr/lib/golang/src/k8s.io/gengo/examples/defaulter-gen/generators (from $GOROOT)
	/home/skitt/go/src/k8s.io/gengo/examples/defaulter-gen/generators (from $GOPATH)
cmd/client-gen/generators/scheme/generator_for_scheme.go:28:2: cannot find package "k8s.io/gengo/generator" in any of:
	/usr/lib/golang/src/k8s.io/gengo/generator (from $GOROOT)
	/home/skitt/go/src/k8s.io/gengo/generator (from $GOPATH)
cmd/client-gen/types/helpers.go:25:2: cannot find package "k8s.io/gengo/namer" in any of:
	/usr/lib/golang/src/k8s.io/gengo/namer (from $GOROOT)
	/home/skitt/go/src/k8s.io/gengo/namer (from $GOPATH)
cmd/client-gen/generators/scheme/generator_for_scheme.go:30:2: cannot find package "k8s.io/gengo/types" in any of:
	/usr/lib/golang/src/k8s.io/gengo/types (from $GOROOT)
	/home/skitt/go/src/k8s.io/gengo/types (from $GOPATH)
cmd/deepcopy-gen/args/args.go:24:2: cannot find package "k8s.io/gengo/examples/deepcopy-gen/generators" in any of:
	/usr/lib/golang/src/k8s.io/gengo/examples/deepcopy-gen/generators (from $GOROOT)
	/home/skitt/go/src/k8s.io/gengo/examples/deepcopy-gen/generators (from $GOPATH)
```

**Comment by tpantelis** [comment]
> > > The generator seems to be somewhat fragile — I had to delete `~/go/src/k8s.io/code-generator` entirely to get this to work — but this will do for now ;-).
> > 
> > 
> > Can you elaborate? Had you previously done 'go get /k8s.io/code-generator'? If so, then it would've been using the current master which generates incompatible code with prior k8s API versions causing compilation errors in subM. Hence the reason for retrieving the prior 1.14 version.
> 
> I had previously run `go get k8s.io/code-generator`, and as a result I didn’t have the dependencies; running the code generator then fails with
> 

yeah - it only checks for the existence of the script file and not the desired release tag version. I suppose we could check the latter as well and check out the desired release tag.

**Comment by tpantelis** [comment]
Merging this now - we can refine it later if needed.

**Pull request merged**
